# Generated by Django 4.2.2 on 2023-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a menu category (e.g. Coffees, Tea, Iced Coffee, Pastries etc.)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this book', to='menu.category'),
        ),
    ]
